apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /tg-openapi
            - name: BASE_URL
              value: /tg-openapi-ui
